### ISSUE TITLE
Design de la page de notes

### ISSUE THREAD

**Issue by jbeaudoin11** [antoineMoPa/glacial#12]
J'ai passé plusieurs heures a jouer avec bootstrap et bien qu'il manque encore des détails pour avoir un plus beau rendu avec un tableau, je n'aime pas dutout...

pourquoi on ferait pas des cards a la place qu'on dispose dans une grille par groupe:
- note des exams et des app (bref les rows du tableau sauf la dernière ligne
- note de chaque GEN (soit la dernière ligne)

par exemple pour un app ça donnerait qqch dans le genre :

![mark](https://cloud.githubusercontent.com/assets/10903391/11766656/f71476a4-a15f-11e5-955b-99101bca839f.png)

c'est très primitif comme rendu, je vais essayer de faire qqch de plus concret avec bootstrap..

**Comment by NewLunarFire** [comment]
J'ai du mal à visualiser ton système pour les notes. C'est plus complexe pour nous vu qu'on a des notes par compétence et pas par cours.

À mon avis il faudrait trier par compétence puis sous-compétence puis évaluation.

**Comment by antoineMoPa** [comment]
Moi j'aime le tableau des notes actuel parce qu'on peut voir toute la session d'un coup. Mais j'aime aussi le concept des cartes, ça organise mieux l'info et ça serait un bon exemple pour les développeurs du site (Rien ne leurs empêche de prendre le code, la licence est GPLv3).

**Comment by jbeaudoin11** [comment]
Voila une bonne partie du résultat !

![wip](https://cloud.githubusercontent.com/assets/10903391/11780079/44cbab2e-a22d-11e5-88d9-ae99067d5384.png)

Il reste beaucoup de travail a faire au niveau du responsive, mais la grille principale marche bien. C'est surtout a l'intérieure que je sais pas si ça marche avec plus de 3 notes pour les GEN..

Et il reste a générer ça :) . Pour l'instant j'ai juste fais un template hardcoder.

**Comment by antoineMoPa** [comment]
Ça a l'air beau!

**Comment by antoineMoPa** [comment]
Ça a l'air beau!

Et avec le design que t'as fait, ça va aller bien parce que c'est pensé pour le mobile.

Un coup que le menu sera plus à gauche, on met les cartes «inline-block» ou en pleine largeur sur mobile et ça va être 1000x mieux que le site actuel.

**Comment by jbeaudoin11** [comment]
Tiens toé !

![sans titre](https://cloud.githubusercontent.com/assets/10903391/11803497/8e6b9b30-a2c9-11e5-97f9-dbdabd64a9da.png)

Un peu batard comme grille, je croyais qu'elle ferait autre chose.. va surement faloir que je change de plugin. Et quelque petit achro sur des notes (NaN)..

Mais c'est quand même cool :)
C'est "responsive", en fait ça fait juste poussé les casses qui sont pu dans l'écran sur la ligne du bas, mais pour l'instant j'ai du fixé une width de 380px pour les cards.

**Comment by antoineMoPa** [comment]
C'est correct de fixer une witdh à cette taille là. Au pire, si l'écran est plus petit:

```
@media all and max-width(380px){
    .lepatente{
        width:100%;
    }
}
```

**Comment by jbeaudoin11** [comment]
c'est quand même beau, mais c'est pas efficace quand on a beaucoup de cases :/
Le plus chiant c'est qu'on peux pas se basé sur sur le nom des carte.. quoi que pt bien avec des regex, mais encore là on sait pas ce que ça peux donné pour des cas d'exception..

Mais je vais penssé a qqch !

**Comment by DonavanMartin** [comment]
Bonjour à tous, 

Je trouve l'idée des cartes intéressante.

Je propose qu'on donne le choix à l'utilisateur soit le modèle du tableau, soit le modèle des cartes. En gardant l'option dans une variable...

Je propose aussi pour le design de la page de notes et du coup le site web en entier ceci: 
Le menu de gauche pourrait être réorganisé selon un top menu bar. Ainsi on gagnerait de l'espace en largeur pour lire les documents. J'ai un début de code si il y a des intéressés, sinon bien je garderai ça en suspend... 

Voici en aperçu de mon idée...
<img width="1031" alt="capture d ecran 2015-12-28 a 12 47 49" src="https://cloud.githubusercontent.com/assets/7544240/12022792/411c0430-ad61-11e5-92be-2e1be035133e.png">

**Comment by antoineMoPa** [comment]
Je suis d'accord de refaire un menu.

Par contre, je ne mettrais pas d'autre sessions dans le menu. (Juste la session actuelle, c'est moins encombrant. L'utilisateur peut toujours aller sur l'autre site). Aussi, je ne mettrais [pas de dropdown](https://blog.kissmetrics.com/common-website-navigation-mistakes/).

Ça serait plus des liens vers:
- La page principale
- L'horaire
- La page de l'APP actuel
- La page de projet
- Les notes

Pour le reste, je laisserais le menu à gauche (version qu'on rend responsive).

Faudrait faire la suite de la discussion sur le menu dans un nouvel _issue_.

**Comment by antoineMoPa** [comment]
Jusqu'à nouvel ordre, on va se concentrer sur des petits hacks qui changent moins le visuel de l'application actuelle.
