### ISSUE TITLE
Failling gracefully

### ISSUE THREAD

**Issue by antoineMoPa** [antoineMoPa/glacial#13]
Supposons que le site change et que ça crée des bugs dans notre extension, il faudrait que l'utilisateur puisse désactiver certaines parties / tout de l'extension.

**Comment by jbeaudoin11** [comment]
Genre inject bootstrap dans toutes les pages et... WTF is going on :3

**Comment by jbeaudoin11** [comment]
Mais je crois que si on change toutes les pages, ça sera beaucoup moins pire. Sauf si une nouvelle page arrive.. Comme on a pas accès a toutes les pages possible (s2, s3 , etc) et bien ça deviens complexe

**Comment by antoineMoPa** [comment]
Bin là on arrive dans une question philosophique: 

Est-ce qu'on refait le site avec l'extension ou on améliore des petits points.

Je pense qu'on est mieux d'avoir une _approche hybride_&trade;:
- Refaire les pages qui posent des gros problèmes (horaire, notes, nouvelles etc.)
- Tweaker en CSS et Javascript ce qui le mérite (Page de projet, page d'APP, menu et header)
- On touche pas à une nouvelle page qui apparait dans le site
  - À par les modifs génériques ( CSS des <a>,<h1>,<h2>, ... )

Je serais aussi en faveur de suggérer à l'équipe qui gère le site d'éventuellement prendre de notre code. Pour ça faudrait trouver une licence ou une manière de céder les copyrights avec l'accord de tous les contributeurs.

**Comment by jbeaudoin11** [comment]
c'est surtout que si on refait certaine page mais pas d'autre, ça sera pas uniforme et ça va etre fucking laid

**Comment by antoineMoPa** [comment]
Oui, mais en même temps, mon dernier point va palier pour ça autant que possible:
- On touche pas à une nouvelle page qui apparait dans le site
  - À par les modifs génériques ( CSS des <a>,<h1>,<h2>, ... )

Messemble qu'on a pas le choix d'afficher toutes les pages qui risquent d'exister pour pas fucker la vie des utilisateurs.
