### ISSUE TITLE
Système de build

### ISSUE THREAD

**Issue by antoineMoPa** [antoineMoPa/glacial#14]
J'avais fait un makefile parce que c'était une manière rapide pour moi de tester, étant sous linux.

Cependant, puisqu'on a déjà besoin de node pour faire l'extension firefox + la packer, je suggère qu'on fasse un petit système de build en javascript exécuté par node et qu'on se débarrasse du makefile. Ça serait p-e plus friendly pour des contributeurs sur windows. Le système pourrait s'occuper de générer le manifest pour chrome.

Est-ce que c'est une bonne idée?

**Comment by jbeaudoin11** [comment]
Garde le makefile, on va appeller celui ci et ainterieure il va appeler node.

Je suis sur windows et la fonction make peu etre rajouter avec un programe.

**Comment by antoineMoPa** [comment]
Ok good
