### ISSUE TITLE
Pondérations manquantes 

### ISSUE THREAD

**Issue by DonavanMartin** [antoineMoPa/glacial#18]
Le problème : les notes cellules du tableau qui contiennent "--" n'ont pas la pondération de la note. Donc, sa limite et complexifie les calculs.

----====----====----====----====----====----====----====----====----====
Une des solutions : 
----====----====----====----====----====----====----====----====----====

```
// Get Ponderation datas from url ponderation
function include_ponderation(){
    var url = window.location.href;
    url = url.replace("notesEtu.php", "ponderation.php");
    $("#Loader").load(url,function(){
        for (i = 0; i < data.length-1; i++) {
            for (j = 0; j < countProperties(data[i])-1; j++) {
                if(data[i][j] != ""){
                    if(typeof dataToolTip[i][j] != 'undefined'){
                        if(typeof dataToolTip[i][j].ponderation != 'undefined'){
                            dataToolTip[i][j].ponderation = data[i][j];
                        }
                    }
                }
            }
        }
    });
}
// Count number of elements in object                                                                                                                                       
function countProperties(obj) {
    var count = 0;
    for(var prop in obj) {
        if(obj.hasOwnProperty(prop))
            ++count;
    }
    return count;
}
```

----====----====----====----====----====----====----====----====----====

Problème lié a cette solution : 
La page de la grille de note et la page des pondérations prennent chacun environ 5 secondes a loader... Donc, la page avec l'extension prendra au moins 10 sec a loader ce qui est vraiment long pour un simple tableau de donné... 

Avons-nous d'autre option ???

**Comment by antoineMoPa** [comment]
### Possibilité:

On load la pondération une fois (Genre à la demande de l'utilisateur (click d'un bouton dans la page de notes), pour pas qu'on ralentisse et frustre son workflow encore plus) et on enregistre les données dans `window.localStorage` ou une des options [ici](http://www.html5rocks.com/en/features/storage).

**Comment by DonavanMartin** [comment]
Problème résolue... 
Seul à la demande de l'utilisateur la grille des pondérations est loader.
