### ISSUE TITLE
Se débarasser des iFrames

### ISSUE THREAD

**Issue by NewLunarFire** [antoineMoPa/glacial#2]
Le site actuellement est fait avec 3 iFrames: 1 pour la barre de titre, 1 pour le menu de gauche et un pour le contenu. Ça cause 2 problèmes:
1. Le menu disparait quand t'ouvres un lien dans un nouvel onglet.
2. Ça cause des problèmes de défilement sur la page. Le menu de gauche scrolle indépendamment du contenu. C'est surtout bad sur mobile, ou des fois t'es juste pas capable de faire scroller le menu pour aller dans les sections que tu veux.

Je suggère donc qu'on remplace les iFrame par des divs avec le même contenu dedans.

**Comment by antoineMoPa** [comment]
Je suis d'accord.

**Comment by antoineMoPa** [comment]
Je peux faire ça dans le temps des fêtes si personne d'autre prend la tâche.

**Comment by NewLunarFire** [comment]
Je pensais peut-être faire ça. J'ai pas énormément de temps avec les examens et le travail en ce moment mais pendant le temps des fêtes surement.

Je suggère aussi qu'on s'attarde pas trop sur le site de la S1 pis qu'on attende d'avoir accès au site de la S2.

**Comment by antoineMoPa** [comment]
Ouais, moi aussi j'attends aux fêtes avant de m'investir plus, faut quand même étudier!

**Comment by DonavanMartin** [comment]
Vous pouvez regarder ce que j'ai pusher sur ce commit: https://github.com/DonavanMartin/glacial/commit/87c7d7dc0ab15bb1a14052e1ecd80b12f9bf9a84

**Comment by antoineMoPa** [comment]
Je vais closer pour l'instant.

Raison:

L'issue est inactive
C'est quand même un gros changement à faire et c'est mieux de se concentrer sur de plus petites modifications qui on un plus gros impact. (Il faut à peut près tout changer le DOM, c'est quand même un peu risqué)
