### ISSUE TITLE
Enlever : data-info=""[{\"0\": [\"\"], \"1\": [\"\"], \"2\": [\"\"], \"3\": [ ... 

### ISSUE THREAD

**Issue by DonavanMartin** [antoineMoPa/glacial#20]
Enlever les datas dans le body data-info=""[{\"0\": [\"\"], \"1\": [\"\"], \"2\": [\"\"], \"3\": [ ... 

Ces données sont présente dans la variable "info"

**Comment by NewLunarFire** [comment]
Heu, tu vois ça où? J'ai cherché plein de pages et j'ai pas trouvé ce à quoi tu fais référence.

**Comment by FelixMartel** [comment]
Plus utilisé depuis l'utilisation d'unsafeWindow. À moins que @DonavanMartin est quelque chose à ajouter, tu peux fermer.
