### ISSUE TITLE
Fonctionnement sur chrome

### ISSUE THREAD

**Issue by FelixMartel** [antoineMoPa/glacial#22]
Voulant tester vos trucs, j'ai dû faire quelques modifs pour que ça fonctionne sur chrome. En particulier, le matches du manifest.json ne matchait pas avant d'être changé pour utiliser le protocole https. Vous pouvez voir ma fork où j'ai aussi merge avec @DonavanMartin.

Joyeux noël!

**Comment by antoineMoPa** [comment]
Nice je vais prendre ça

**Comment by antoineMoPa** [comment]
Je me suis rendu compte que le site est aussi accessible avec http (sans `https`). J'ai donc changé pour `*://` au lieu de `https://`. Maintenant les deux fonctionnent!

À part de ça, j'ai _mergé_, donc je _close_.

**Comment by antoineMoPa** [comment]
Merci pour ta contribution de Noël :santa: !

**Comment by FelixMartel** [comment]
Mais de rien! Ce sont déjà des features sympathiques à avoir.
Bien vu, je ne peux pas utiliser la version http et suis redirigé automatiquement vers la version https probablement à cause de [ça](https://www.chromium.org/hsts).

**Comment by NewLunarFire** [comment]
Yo gang. Au lieu de simplement mettre un wildcard, mettez _http[s]?_ dans la Regex. Ça va matcher http et https mais aucun autre protocole

**Comment by antoineMoPa** [comment]
Ça serait effectivement plus précis

**Comment by NewLunarFire** [comment]
En fait non. J'ai vérifié et cette string là n'est pas une RegEx mais un Chrome Match Pattern: https://developer.chrome.com/extensions/match_patterns

Donc on laisse comme ça.
