### ISSUE TITLE
Structure des notes

### ISSUE THREAD

**Issue by DonavanMartin** [antoineMoPa/glacial#23]
Les structures : data, datatooltip pourraient devenir simple et très utiles si l'information est organisée différemment. Le problème est que ces structures prennent les informations en rangées et que les informations des cours sont distribuées en colonnes. 

Alors,j'ai commencé une structure sur les données qui aidera sans doute la manipulation des données de la grille de notes et de pondération. En résumé, toutes les informations sont dans 1 seule variable, et ceci comprend les pondérations manquantes... 

```
Exemple:
var lessons: {                                   // Tableau des cours
         "id" : "GEN101,                         // Code du cours
         "skills" : {                            // Tableau des compétence
                "evaluations" : {                // Évaluations 
                         "note" : "--",          // Notes obtenues et restants("--")
                         "ponderation" : 50,     // Ponderation (lié à grille des pondérations)
                 },
         },
},
```

Qu'en pensez-vous?

**Comment by antoineMoPa** [comment]
Je pense que c'est une bonne idée d'inclure toutes les pondérations. On a déjà une structure de donnée dans `get_data`:

https://github.com/antoineMoPa/glacial/blob/master/common/addons/marks.js

Faudrait juste faire «fitter» ça.

**Comment by antoineMoPa** [comment]
Puisque je close massivement des issues qui sont inactive, je close.
(Rien n'empêche de réouvrir, juste me contacter)
