### ISSUE TITLE
Bouton afficher/cacher grille de pondération ne marche pas dans firefox

### ISSUE THREAD

**Issue by antoineMoPa** [antoineMoPa/glacial#24]
Dans chrome, tout semble fonctionner.

Dans firefox, le bouton reste sur «Téléchargement...».

@DonavanMartin, pourrais-tu investiguer ça?

**Comment by DonavanMartin** [comment]
MutationObserver ne devrait pas causer de problème selon http://caniuse.com/#feat=mutationobserver 
Donc soit la page afficher est différente,
soit les éléments de la pages apparait à différents moment (j'ai déjà investit plusieurs heures dessus...)

**Comment by antoineMoPa** [comment]
Ok, je vais essayer de trouver le problème quand j'aurai un peu de temps!

**Comment by FelixMartel** [comment]
Évaluer le script avec unsafeWindow.eval() au lieu de laisser jQuery l'évaluer semble foncitonner. Je vais publier un fix un jour. Sinon unsafeWindow ça pourrait être pratique pour aller chercher les variables de la page sans passer par JSON.stringify.

**Comment by antoineMoPa** [comment]
Je trouve qu'il y a quelque chose d'étrange à afficher la grille de pondération quand il y a déjà une page pour ça. (Point de vue utilisateur)

Puisqu'on veut faire une `release` rapide, je vais cacher ça pour l'instant, et on prendra la décision de laisser la grille ou d'enlever le code qui l'affiche. (Genre on la laisse display:none;)

**Comment by FelixMartel** [comment]
Je crois que son utilité se trouve plutôt dans l'ajout des pondérations manquantes à la grille de note/info-bulle machin pour les évaluations à venir.

**Comment by antoineMoPa** [comment]
Effectivement.

**Comment by antoineMoPa** [comment]
Ce bug a été réglé
