### ISSUE TITLE
Rendre horarius responsive

### ISSUE THREAD

**Issue by antoineMoPa** [antoineMoPa/glacial#3]
Vue pour la journée actuelle qui affiche chaque cours, le local, l'heure, et les autres infos qu'on peut extraire en javascript ou par le fichier ical.

Possibilité d'aller à la journée suivante/précédente avec un «swipe».

Wireframe:

<img src="https://cloud.githubusercontent.com/assets/2675724/11752851/d12f0a72-a00f-11e5-8f19-71cb54ab54a8.png" width="200px">

**Comment by jbeaudoin11** [comment]
Est-ce que les addons firefox pour mobile sont exactement comme pour ordit ?

**Comment by antoineMoPa** [comment]
j'ai aucune idée pour l'instant

**Comment by NewLunarFire** [comment]
https://developer.mozilla.org/en-US/Add-ons/SDK/Tutorials/Mobile_development

Faut utiliser jpm-mobile au lieu de jpm. Sinon c'est le même code.
