### ISSUE TITLE
Signature des extensions sur Firefox

### ISSUE THREAD

**Issue by NewLunarFire** [antoineMoPa/glacial#31]
Salut gang,

Firefox 43 nous a fait la surprise de refuser l'installation de add-ons si elles ne sont pas signées. Pour l'instant, on peut aller dans _about:config_ et désactiver l'option _xpinstall.signatures.required_. Mais dès la prochaine version de Firefox, cette option ne sera plus possible et il faudra absolument signer nos extensions si on veut qu'elle fonctionne dans Firefox.

La version Developper va laisser la switch _xpinstall.signatures.required_ disponible pour qu'on puisse développer le add-on dessus mais il faut faire signer nos releases, on ne pourra pas s'en passer.

**Comment by FelixMartel** [comment]
Même chose sur chrome en passant, les extensions doivent être sur le chrome store sinon elles sont automatiquement désactivées. Un workaround est de les installer en tant que unpacked extension.

**Comment by NewLunarFire** [comment]
Pour Firefox, j'ai pu me créer un compte en deux minutes et signer l'extension, c'est pas un problème. Si tu vas sur https://newlunarfire.github.io, tu peux juste cliquer sur le bouton Installer pour Firefox et le tour est joué.

Pour Chrome on peut toujours publier sur le webstore en mode Unlisted. On donne aux étudiants de gegi un lien pour y accéder et downloader l'application, mais elle apparait pas dans les résultats de recherche du webstore.

Sinon, ayant pu signer l'extension sur Firefox je considère ce issue comme fermé.
