### ISSUE TITLE
Accents aigus & autres dans le téléchargement des documents

### ISSUE THREAD

**Issue by antoineMoPa** [antoineMoPa/glacial#38]
Il faudrait les enlever ou s'arranger pour qu'ils s'affichent correctement.

**Comment by FelixMartel** [comment]
Ils s'affichent correctement, non?

**Comment by antoineMoPa** [comment]
Je parle de quand on télécharge tous les documents avec le truc qui fait un zip

**Comment by FelixMartel** [comment]
À moins que tu fasses référence à un truc différent, je ne suis pas capable de reproduire ce problème. J'ai déjà eu un truc similaire pour Chrome et ajouter https://github.com/antoineMoPa/glacial/blob/a8a1705005c45474946294f151a73a10c5d0755d/chrome/main.js#L22 l'a réglé. Firefox semblait ne pas avoir ce problème sur ma machine.

**Comment by antoineMoPa** [comment]
Bon, je vais réessayer ce soir!

**Comment by antoineMoPa** [comment]
Effectivement, le problème est réglé.

Source de mon erreur: Je me suis rendu compte que j'avais 2 versions de l'extension activée sur mon chromebook (La nouvelle ainsi qu'une plus ancienne qui n'avait pas été désactivée). Fail.
