### ISSUE TITLE
Convention sur JQuery

### ISSUE THREAD

**Issue by jbeaudoin11** [antoineMoPa/glacial#4]
Je suis vraiment pas d'accord avec ça ! Dans le monde d’aujourd’hui, c'est très très rare que tu vas avoir un site web sans JQuery et si des gens veulent contribuer, apprendre JQuery est probablement la meilleur chose qui peuvent leur arrivé dans la vie :)

**Comment by jbeaudoin11** [comment]
Et rajouter qu'on utilise des tabulations a la place de 4 espaces SVP !
Configurez vos éditeurs...

**Comment by antoineMoPa** [comment]
What about [Zepto](http://zeptojs.com/) qui est identique à jQuery. (mis à part que ça ne supporte pas IE8), si t'aimes pas le javascript pur?

Et devant ce nouvel épisode de «tabs vs spaces», je sais pas trop quoi répondre.

**Comment by antoineMoPa** [comment]
Bon j'ai ôté ces lignes là de mon `.emacs`, maintenant je vais faire des tabs:

```
;(setq c-default-style "linux"                                                                                                                                              
;          c-basic-offset 4)                                                                                                                                                
;(custom-set-variables                                                                                                                                                      
; '(tab-width 4))                                                                                                                                                           

;(setq-default indent-tabs-mode nil)                                                                                                                                        
;(setq-default tab-width 4)                                                                                                                                                 
;(setq indent-line-function 'insert-tab)                                                                                                                                    
;(setq sgml-basic-offset 4)
```

J'avais pris tellement de temps à le faire marcher avec 4 espaces  :cry:

**Comment by jbeaudoin11** [comment]
Zepto ? maybe not http://zurb.com/article/1293/why-we-dropped-zepto
et si tu fais les testes, tu vois très bien que jquerry est bien mieux

vs querySelector ou querySelectorAll
http://stackoverflow.com/questions/11503534/jquery-vs-document-queryselectorall

bref jquery is love jquery is life :)

les espaces c'est juste chiant...

**Comment by antoineMoPa** [comment]
Je suis vraiment un adepte du Javascript pur (alias vanilla js) et c'est la direction que j'aurais donné au projet si j'avais à codé ça seul dans mon sous-sol.

Mais bon t'as l'air de vraiment tenir à jQuery et je pense que les autres vont apprécier aussi. Je vais enlever ça des conventions.

:elephant:

**Comment by NewLunarFire** [comment]
À mon humble avis jQuery est pas nécéssairement mieux que vanilla js (et je préfère vanilla). Mais des fois c'est une question de choisir une plateforme avec laquelle un maximum de gens sont à l'aise ou expérimentés, et anyway quand tu cherches dans StackOverflow maintenant la solution à tout c'est "fait x et y avec jQuery".
