### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by jbeaudoin11** [antoineMoPa/glacial#5]
J'ai remarquer que le gros problème de performance ne viens pas du nombre de script a loader, mais bien du call a notesEtu.php.. La plus part des fichiers sont en caches.

![glacial](https://cloud.githubusercontent.com/assets/10903391/11761184/17812de0-a086-11e5-81b6-9faadf17c4a2.png)

Et perso j'ai aucune idée comment on peut faire en sorte d'accélérer ça via un plugin... Le problème c'est le serveur de l'uni qui rush. Surement lors de la génération des notes, leur base de donnée doit être bien remplis.

**Comment by antoineMoPa** [comment]
Ohh, effectivement, je faisais mes tests en vidant le cache donc les scripts prenaient la majorité du temps.

Puisque la page elle même est vraiment lente et qu'on peut rien y faire, on pourrait au moins mettre une icone de loading pendant ces 3.7 secondes d'attente. (Ou un gif random)

<img src="http://www.ajaxload.info/cache/FF/FF/FF/00/00/00/5-0.gif">

**Comment by NewLunarFire** [comment]
On met un chat!

**Comment by antoineMoPa** [comment]
Shoot une proposition :stuck_out_tongue_winking_eye:

**Comment by NewLunarFire** [comment]
Ça. Et on change le texte pour "We're improving your GEL experience. Please enjoy this dancing cat while you wait."

![Chat qui danse](https://lh3.googleusercontent.com/-6TZEhNdCP2Q/VXS0Mt0kS3I/AAAAAAAADMg/Hdc0MFpMJJE/w338-h442/14+-+1.gif)

**Comment by antoineMoPa** [comment]
Le seul problème c'est qu'il faut une image compatible avec la licence de notre extension et j'ai de la misère à trouver la source originale du chat!

**Comment by jbeaudoin11** [comment]
Hahahaha nice xD
