### ISSUE TITLE
Faire marcher l'extension dans chrome

### ISSUE THREAD

**Issue by antoineMoPa** [antoineMoPa/glacial#6]
J'ai fait un bout du travail en faisant marcher l'injection de script javascript. Pour le CSS, je pense qu'on peut juste toujours l'inclure, au pire, les règles css ne s'appliqueront pas. Sinon, on patente une injection CSS comme [ça](http://stackoverflow.com/questions/5452957/add-css-to-pages-through-a-css-file)

J'ai essayé `chrome.tabs.injectScript()`, mais puisque c'est pas un background script, ça ne marchait pas. Sinon, il y a l'option de matcher des urls directement dans le manifest.json, mais ça fitterait mal avec le code pour firefox. On peut aussi se créer un background script.

Reste à faire fonctionner addon/mark. Le plus simple serait surement d'ajouter un worker à chrome comme ça la syntaxe dans l'addon serait pareille pour firefox et chrome.

**Comment by NewLunarFire** [comment]
On peut toujours changer le CSS avec du HTML DOM, genre `document.getElementById("header").style.color = "red";`

**Comment by jbeaudoin11** [comment]
Perso jai aucune idee pour chromd, japprend beaucoup en se moment pour firefox.. je me concentre seulement sur celui ca!

Amusez vous

**Comment by jbeaudoin11** [comment]
Mais je viens de faire quelque recherche et je crois que le plus simple est d'utiliser une platforme cross-browser ?

Genre Kango ?
http://kangoextensions.com/

Ca semble etre le plus cool a utiliser et cest gratuit pour l'opensource

**Comment by jbeaudoin11** [comment]
Quoi que crossrider semble aussi une bonne option

https://jvaneyck.wordpress.com/2013/03/02/creating-cross-browser-extensions-with-crossrider/

**Comment by jbeaudoin11** [comment]
Je ne suis toujours pas convaincu des 2 solutions... Ce n'est pas claire s'il est possible de faire des plugins pour mobile donc pour l'instant il est mieux de continuer dans le chemin que nous avons prit.

Essayons de glue toute ça pour que ça soit compatible.

J'ai réalisé que oui j'ai du code Firefox dans marks.js ! Je vais revoir mon approche des fichiers modulaires. Je comprend un peu plus comment chrome fais l'injection via le manifest.

Il va falloir générer le manifest selon moi :P.
On a juste a créer un petit script node appeler dans le makefile...
on vera ça en temps et lieux.

**Comment by NewLunarFire** [comment]
C'est possible de faire un plugin pour Firefox mobile. C'est exactement comme pour desktop mais avec jpm-mobile à la place, vu que Firefox mobile utilise pas XUL.

**Comment by antoineMoPa** [comment]
Bin le système modulaire fonctionne déjà à mon dernier commit dans chrome, c'est juste moins clean que si on générait le manifest comme Jimmy propose (Je pense que c'est la meilleure solution).

Pour les outils de développement cross-browser, on dirait que certaines options sont gratuites, mais pas libres. Et je trippe pas de dépendre sur un truc non libre personnellement. C'est sur que ça reste une option si ça devient trop dur de supporter les browser qu'on veut.

Probablement qu'il y a assez d'apple freaks en génie élec/info anyway pour faire fonctionner l'extension avec safari. Alors, 98% des cas seront réglés avec chrome, firefox et safari.

Un coup que ça marche bien, on peut extraire un framework open-source de notre extension pour faire des extensions cross-browsers. Ça serait vraiment épic.
