### ISSUE TITLE
Trouver un meilleur nom?

### ISSUE THREAD

**Issue by antoineMoPa** [antoineMoPa/glacial#7]
On s'entend qu'un jeu de mot entre «gel» et «glacial», on peut trouver mieux.

**Comment by NewLunarFire** [comment]
Non sérieux moi je trouve ça cool. C'est court et facile à retenir.

**Comment by jbeaudoin11** [comment]
Moi glacial  jaime bien, le gel me gosse un peu devant haha

**Comment by antoineMoPa** [comment]
J'avoue, juste glacial, ça serait vendeur.

**Comment by antoineMoPa** [comment]
Maintenant c'est `glacial`. Pas obligé d'updater les `git remote` et autres, github route automatiquement vers le bon repo même en utilisant la vieille url.

P-e juste mettre à jour le nom de vos forks (Si ça vous tente).

**Comment by jbeaudoin11** [comment]
Close stp !
